### ISSUE TITLE
Tag current release and advertise OpenUPM support

### ISSUE THREAD

**Issue by randomPoison** [nementic-games/time-tools#3]
Would it be possible to add a tag (optionally setup via a GitHub release) for the latest version of time-tools? I ask because this package is [listed on OpenUPM](https://openupm.com/packages/com.nementic.time-tools/) but currently cannot be downloaded because there are no tagged releases. The tag just needs to be a valid semver string, so something like `v1.0.0` to match the current package version should work.

Also, if you're interested in better supporting accessing the package via OpenUPM, you can add instructions for doing so to your README. For projects that aren't already using Git as version control system, pulling in the package as a Git dependency can be inconvenient since it means all team members need to install Git on their development machines in order to load the project. Making the package available via OpenUPM ensures that the project can still be opened without needing Git as a dependency.

Also, thanks a ton for putting together this package! I've found it to be very useful and appreciate the contribution to the UPM ecosystem :heart:

**Comment by chrisyarbrough** [comment]
Thanks for letting us know about OpenUPM. We're definitely interested in distributing our open-source packages via UPM. There's some work going on behind the scenes to make releasing these packages easier, but I'll make sure the current versions are tagged manually for now.

**Comment by randomPoison** [comment]
Awesome, thanks a ton! The package is now showing up correctly on OpenUPM 👍
